//alert("Bienvenido");
var boleta, nombre, grupo, materia, fecha;
boleta=prompt("Ingrese su boleta:");
nombre=prompt("Ingrese su nombre:");
grupo=prompt("Ingrese su grupo:");
materia=prompt("Ingrese su materia:");
fecha=prompt("Ingrese alguna fecha:");
alert(`Su boleta es: ${boleta}`);
alert(`Su nombre es: ${nombre}`);
alert(`Su grupo es: ${grupo}`);
alert(`Su materia es: ${materia}`);
alert(`La fecha que ingreso es: ${fecha}`);
